
pub const DEFAULT_SEASON_TIMER: u64 = 24 * 60 * 60;

pub const DEFAULT_LEADERBOARD_MAX_GAME_COUNT: u8 = 10;
pub const DEFAULT_MAX_WINNER_COUNT: u8 = 10;

pub const DEFAULT_MAX_PLAYER_PER_TEAM: u16 = 350;
pub const DEFAULT_LEADERBOARD_MIN_SCORE: u32 = 0;
pub const DEFAULT_LEADERBOARD_MIN_TILE: u16 = 2;